
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leoal
 */
public class Brasileirao2026 extends javax.swing.JFrame {
    String[] times = {"Atlético-MG" , "Athlético-PR", "Bahia", "Botafogo",
                "Bragantino", "Chapecoense", "Corinthians", "Coritiba",
                "Cruzeiro", "Flamengo", "Fluminense", "Grêmio", "Internacional",
                "Mirassol", "Palmeiras", "Remo", "Santos", "São Paulo", "Vasco"
                , "Vitória"};
    
    int[] forca = {
    22, 37, 39, 40,
    30, 18, 9, 30,
    42, 99, 46, 25,
    27, 35, 95, 15,
    17, 44, 40, 33};
    
    int[] pontos;
    int[] vitorias;
    int[] empates;
    int[] derrotas;
    int[] golsPro;
    int[] golsContra;
    /**
     * Creates new form Brasileirao2026
     */
    public Brasileirao2026() {
        initComponents();
        tblClssf.setVisible(false);
        tblJgs.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        teamsLst = new javax.swing.JList<>();
        btnGer = new javax.swing.JButton();
        btnLmp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClssf = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblJgs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teamsLst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Atlético-MG", "Athlético-PR", "Bahia", "Botafogo", "Bragantino", "Chapecoense", "Corinthians", "Coritiba", "Cruzeiro", "Flamengo", "Fluminense", "Grêmio", "Internacional", "Mirassol", "Palmeiras", "Remo", "Santos", "São Paulo", "Vasco", "Vitória" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(teamsLst);

        btnGer.setText("Gerar");
        btnGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerActionPerformed(evt);
            }
        });

        btnLmp.setText("Limpar");
        btnLmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLmpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TIMES");

        tblClssf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Pts", "V", "E", "D", "SG", "GP", "GC"
            }
        ));
        jScrollPane4.setViewportView(tblClssf);

        tblJgs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblJgs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGer)
                            .addComponent(btnLmp))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLmp)
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int gerarGols() {

        int r = (int)(Math.random() * 100);

        if (r < 20) return 0;
        else if (r < 50) return 1;
        else if (r < 75) return 2;
        else if (r < 90) return 3;
        else if (r < 97) return 4;
        else if (r < 99) return 5;
        else return 6;
    }
    
    private void atualizarTabela(int i, int j, int golsA, int golsB) {

        golsPro[i] += golsA;
        golsContra[i] += golsB;

        golsPro[j] += golsB;
        golsContra[j] += golsA;

        if (golsA > golsB) {
            pontos[i] += 3;
            vitorias[i]++;
            derrotas[j]++;
        } else if (golsB > golsA) {
            pontos[j] += 3;
            vitorias[j]++;
            derrotas[i]++;
        } else {
            pontos[i] += 1;
            pontos[j] += 1;
            empates[i]++;
            empates[j]++;
        }
    }
    
    private void btnGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerActionPerformed
        tblClssf.setVisible(true);
        tblJgs.setVisible(true);
        
        String[] colunas = {"Time", "Pts", "V", "E", "D", "GP", "GC", "SG"};

        DefaultTableModel model = new DefaultTableModel(colunas, 0);
        
        String[] colunasJogos = {"Local", "Placar", "Visitante"};
        
        javax.swing.table.DefaultTableModel modelJogos =
    new javax.swing.table.DefaultTableModel(colunasJogos, 0);
        
        
        
        pontos = new int[times.length];
        vitorias = new int[times.length];
        empates = new int[times.length];
        derrotas = new int[times.length];
        golsPro = new int[times.length];
        golsContra = new int[times.length];
        
        for (int i = 0; i < times.length; i++) {
            for (int j = 0; j < times.length; j++) {

                if (i != j) {

                    int golsA = gerarGols();
                    int golsB = gerarGols();

                    if (Math.random() < 0.55) golsA++;

                    int diff = forca[i] - forca[j];

                    if (diff > 0 && Math.random() < diff / 50.0) {
                        golsA++;
                    } else if (diff < 0 && Math.random() < (-diff) / 50.0) {
                        golsB++;
                    }
                    
                    if (forca[i] > 90 && golsA < golsB && Math.random() < 0.5) {
                        golsA = golsB;
                    }

                    modelJogos.addRow(new Object[]{
                        times[i],
                        golsA + " x " + golsB,
                        times[j]
                    });
                    
                    if (Math.random() < 0.15) {
                        golsB = golsA;
                    }

                    atualizarTabela(i, j, golsA, golsB);
                }
            }
        }
        
        for (int i = 0; i < times.length; i++) {
            for (int j = i + 1; j < times.length; j++) {
                if (pontos[j] > pontos[i]) {
                    if (pontos[j] > pontos[i]) {

                        int temp = pontos[i];
                        pontos[i] = pontos[j];
                        pontos[j] = temp;

                        String tempT = times[i];
                        times[i] = times[j];
                        times[j] = tempT;

                        temp = golsPro[i];
                        golsPro[i] = golsPro[j];
                        golsPro[j] = temp;

                        temp = golsContra[i];
                        golsContra[i] = golsContra[j];
                        golsContra[j] = temp;

                        temp = vitorias[i];
                        vitorias[i] = vitorias[j];
                        vitorias[j] = temp;

                        temp = empates[i];
                        empates[i] = empates[j];
                        empates[j] = temp;

                        temp = derrotas[i];
                        derrotas[i] = derrotas[j];
                        derrotas[j] = temp;
                    }
                }
            }
        }
        for (int i = 0; i < times.length; i++) {

            int saldo = golsPro[i] - golsContra[i];

            model.addRow(new Object[]{
                times[i],
                pontos[i],
                vitorias[i],
                empates[i],
                derrotas[i],
                golsPro[i],
                golsContra[i],
                saldo
            });
        }
        
        
        
        tblClssf.setModel(model);
        
        tblJgs.setModel(modelJogos);
        
        tblClssf.getColumnModel().getColumn(0).setPreferredWidth(150);
    }//GEN-LAST:event_btnGerActionPerformed

    private void btnLmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLmpActionPerformed
        javax.swing.table.DefaultTableModel modelJogos =
        (javax.swing.table.DefaultTableModel) tblJgs.getModel();
    modelJogos.setRowCount(0);

        javax.swing.table.DefaultTableModel modelClssf =
            (javax.swing.table.DefaultTableModel) tblClssf.getModel();
        modelClssf.setRowCount(0);

        tblJgs.setVisible(false);
        tblClssf.setVisible(false);
        
        pontos = null;
    vitorias = null;
    empates = null;
    derrotas = null;
    golsPro = null;
    golsContra = null;
    
    tblJgs.clearSelection();
    tblClssf.clearSelection();
    }//GEN-LAST:event_btnLmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Brasileirao2026.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Brasileirao2026.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Brasileirao2026.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brasileirao2026.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Brasileirao2026().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGer;
    private javax.swing.JButton btnLmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblClssf;
    private javax.swing.JTable tblJgs;
    private javax.swing.JList<String> teamsLst;
    // End of variables declaration//GEN-END:variables
}
